# Generated by Django 4.1.3 on 2022-11-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khudra', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
