# Generated by Django 4.1.3 on 2022-11-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khudra', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='List',
        ),
    ]
