# Generated by Django 4.1.3 on 2023-02-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khudra', '0007_customer_rename_adress_order_note_remove_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
